### ISSUE TITLE
Early crash

### ISSUE THREAD

**Issue by peroveh** [microsoft/OpticSim.jl#373] opened 2022-02-23 12:34 UTC
After installing, i tried executin the first test example: 
using OpticSim
Vis.draw(SphericalLens(OpticSim.GlassCat.SCHOTT.N_BK7, 0.0, 10.0, 10.0, 5.0, 5.0))
Crashes in pre-compile 

using OpticSim
Vis.draw(SphericalLens(OpticSim.GlassCat.SCHOTT.N_BK7, 0.0, 10.0, 10.0, 5.0, 5.0))

Ubuntu 20.04
![image](https://user-images.githubusercontent.com/16647600/155320280-e74fc06e-0fba-4297-bf88-3c34b4d345f3.png)

**Comment by friggog** [comment] 2022-02-24 03:34
@BrianGun did you remove SCHOTT recently? Maybe just missed updating the examples too?

**Comment by peroveh** [comment] 2022-02-24 11:47
I am a bit confused by requirements to Julia version here also. I initially tried with 1.5,... then 1.7 (as specified by the GlassCatalog). 1.6, as specified in the OpticSim.jl I could not find with the proper compiler (1.6.5 only available),, So: Uncertain which version(s) of julia available at https://julialang.org/downloads/ should I use, AND, may i just use Pkg to install the OpticSim thereafter (with version explicit?)

**Comment by peroveh** [comment] 2022-02-24 13:48
Ok... the [64-bit (musl)](https://julialang-s3.julialang.org/bin/musl/x64/1.7/julia-1.7.2-musl-x86_64.tar.gz)[[1](https://julialang.org/downloads/#musl-fn)] was broken... but the https://julialang-s3.julialang.org/bin/linux/x64/1.6/julia-1.6.5-linux-x86_64.tar.gz worked... (barring some Gtk messages).. However , the Pluto notebook seems to fail: 
![image](https://user-images.githubusercontent.com/16647600/155536024-61a59371-4ce4-4f0e-ae9b-4d130ac1f0eb.png)

**Comment by peroveh** [comment] 2022-02-24 13:52
And first non-notebook test: Vis.draw(SphericalLens(OpticSim.GlassCat.SCHOTT.N_BK7, 0.0, 10.0, 10.0, 5.0, 5.0))

**Comment by BrianGun** [comment] 2022-02-24 18:07
@peroveh @friggog this is a result of a long-standing problem (which is solved in the latest version of the code on github, but not in a released version in the Julia registry). 

For copyright reasons we can't include the precompiled glass types with our code. We have to download the glass files from the manufacturer's websites at build time. Sometimes this fails. Schott, in particular, is prone to changing its website in ways that prevent their glass files from being downloaded and Schott glasses are used in many of the examples.

If you clone the latest version of the software from github you shouldn't have this problem. All the examples have been rewritten to use precompiled generic glass types rather than the downloaded SCHOTT files. 

If any of the examples don't work please let me know and I will fix them quickly.

We should make a new release on the Julia registry but have been preoccupied with other things.

**Comment by BrianGun** [comment] 2022-02-24 18:26
> I am a bit confused by requirements to Julia version here also. I initially tried with 1.5,... then 1.7 (as specified by the GlassCatalog). 1.6, as specified in the OpticSim.jl I could not find with the proper compiler (1.6.5 only available),, So: Uncertain which version(s) of julia available at https://julialang.org/downloads/ should I use, AND, may i just use Pkg to install the OpticSim thereafter (with version explicit?)

@peroveh We are currently supporting 1.7.2. Just haven't had time to update the Readme.

**Comment by BrianGun** [comment] 2022-02-24 23:42
Spoke too soon. Some of the examples have been updated to not depend on the Schott library. But the examples in the documentation still use Schott and those will fail. Will fix as soon as time is available.

**Comment by peroveh** [comment] 2022-02-25 11:38
@briangun
Appreciate the quick response here.. wrt the Schott etc..
I am not too familiar with Julia so just to verify.
-In a clean directory I start julia 1.7.2 and create a project
Pkg> activate .)
Pkg> add <https://github.com/microsoft/OpticSim.jl.git> ( or should i use Pkg> dev ...)?
Or should I use another branch/tag ?

Any other "dependencies" that should be added (trying above, i ran into errors precompiling... for example some Gtk stuff)

OR
I have totally done this the wrong way ;-)

**Comment by BrianGun** [comment] 2022-02-25 22:25
@peroveh  The difference between add and dev is not entirely clear to me and the documentation on this point, at least to me, is ambiguous. If you add the package from the github repo I think you'll be in good shape. 

The dependencies should all be in the Project.toml file. You may have to enter the package manager mode and do an instantiate to get all the dependencies loaded. If Gtk is not precompiling that is probably not a problem with OpticSim. I haven't had that particular problem but every computer is slightly different.

**Comment by BrianGun** [comment] 2022-02-28 17:18
@peroveh The project.toml file should not have a direct reference to Gtk. The warning message you are seeing is caused by Luxor. They are adding support for Latex to that package and release a version of the code that doesn't quite work yet. If the warning bothers you file an issue on the Luxor.jl website. 

The warning shouldn't cause any problems with OpticSim. You didn't show the full output of your run but if the Luxor warning is the only problem then OpticSim probably installed correctly. Did you try running any OpticSim code?

**Comment by BrianGun** [comment] 2022-02-28 23:06
This does not sound like an OpticSim problem, more likely you have old packages that are incompatible one with another. Before you start up OpticSim go into the package manager and update all your packages: ]update. They try using OpticSim.

**Comment by peroveh** [comment] 2022-03-01 07:55
Still on Windows... You are right.. I could actually use OpticSim aftert the warning. However the "old" sin of SCHOTT re-appeared, so I may be using the wrong git download...  What would be the exact command and link to get the correct version of the OpticSim with the new glass catalog?
Also, somewhat disturbing,, after the SCHOTT crash, the Julia repl seems to put glue in the pc... the total cpu usage is not extreme, but even writing in to a browser is slowed down to a crawl... (buffering up seconds of keyboard input). Immediately fixed when closing the REPL...
![image](https://user-images.githubusercontent.com/16647600/156127956-7541d190-5349-49a1-b376-fed8a6370993.png)

**Comment by peroveh** [comment] 2022-03-01 09:40
Hm... Apparently closed it by mistake...
As I am getting different warning/errors on W11 and Linux Ubuntu 20.04, it may be good to select the one you use..so i can replicate directly your suggested commands for install?
Since the REPL apparently ends up using some key PC resources (Even the keyb input in the browser has slowed down), i now switch back to Ubuntu20.04.

In a clean directory I do the following: 



![image](https://user-images.githubusercontent.com/16647600/156144093-74dc455d-556f-405b-a072-479ec4b8a3ef.png)


Resulting in the Error

![image](https://user-images.githubusercontent.com/16647600/156144286-2cf3f311-b2b0-45a0-a501-6938ed9d6bc4.png)

**Comment by BrianGun** [comment] 2022-03-01 16:31
@peroveh it looks like you are taking a screen shot of the REPL and pasting that into the comment window. Instead could you copy the text (on WIndows you mark with the mouse and then use CTRL-Shift-C to copy) and then paste the text into the comment window? If you put enclose the text in triple tick marks ``` then github will format it as code. This makes it easier to read. 

Also copy and paste the entire output so I can see where the error is coming from. Include all the using statements, etc. That will help me debug the SCHOTT problem. 

As for the slow REPL that is not an OpticSim problem that is a Julia on Windows problem. See [Slow Keyboard Response](https://discourse.julialang.org/t/serious-issue-julia-language-keyboard-lag-typing-very-slow/32081/21) on Julia Discourse. I think it has something to do with a Package called Winston and Gtk. Gtk I have read can be very slow on Windows. The Discourse thread might have a solution for you, otherwise use Linux, I've never had the problem on Linux.

**Comment by BrianGun** [comment] 2022-03-01 17:38
looks like Gtk is not installing correctly. This is not an OpticSim problem. Not sure why it's not working on your machine. I've never had this particular issue. Maybe raise an issue on the Gtk.jl github repo?

**Comment by BrianGun** [comment] 2022-03-11 19:06
@peroveh  have you managed to get this to work? It seems that the problems mainly lie with packages other than OpticSim. If I don't hear from you in a week or so I'll close this issue.

**Comment by highflyer737** [comment] 2022-05-12 17:17
I just discovered OpticSim yesterday so I'm very new, but very excited by the possibilities. 

I'm having a similar problem. (Is this a duplicate of #368?)

In the REPL:
```
(os) pkg> st
      Status `~/julia/os/Project.toml`
  [24114763] OpticSim v0.6.0 `https://github.com/microsoft/OpticSim.jl.git#main`

julia> using OpticSim

julia> Vis.draw(SphericalLens(OpticSim.GlassCat.SCHOTT.N_BK7, 0.0, 10.0, 10.0, 5.0, 5.0))
UndefVarError: SCHOTT not defined
^       run_main_repl ./client.jl:379
         signature
          run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
         source
                  invokelatest(REPL_MODULE_REF[]) do REPL
                      term_env = get(ENV, "TERM", @static Sys.iswindows() ? "" : "dumb")
                      term = REPL.Terminals.TTYTerminal(term_env, stdin, stdout, stderr)
                      banner && Base.banner(term)
                      if term.term_type == "dumb"
                          active_repl = REPL.BasicREPL(term)
        exec_options ./client.jl:309
         signature
          exec_options(opts::Base.JLOptions)
         source
                  run_main_repl(interactiveinput, quiet, banner, history_file, color_set)
              end
              nothing
          end

          function load_julia_startup()
        _start ./client.jl:495
         signature
          _start()
         source
                  exec_options(JLOptions())
              catch
                  invokelatest(display_error, current_exceptions())
                  exit(1)
              end
 >            if is_interactive && get(stdout, :color, false)
```

I see a similar error in Pluto:
```
begin
	import Pkg
	Pkg.activate("/home/myusernam/julia/os")
	Pkg.add(url = "https://github.com/microsoft/OpticSim.jl.git")
	using OpticSim
end
```
```
Vis.draw(SphericalLens(OpticSim.GlassCat.SCHOTT.N_BK7, 0.0, 10.0, 10.0, 5.0, 5.0))
```
Gives:
```
UndefVarError: SCHOTT not defined

    1. getproperty(::Module, ::Symbol)@Base.jl:35
    2. top-level scope@[Local: 1](http://localhost:1234/edit?id=a45b84b4-d20b-11ec-1f8c-2bbeed8b6df8#)[inlined]
```

I'm using julia version 1.7.2 (2022-02-06) on Ubuntu 22.04 LTS WSL.

Thanks!

**Comment by BrianGun** [comment] 2022-05-12 19:09
Our glass catalogs are downloaded from publicly available sources when OpticSim is installed, directly from the manufacturer's websites in many cases. Shott keeps moving their catalog on the website so the software can't find it. Most of the other manufacturer's catalogs download successfully.

The latest version of the software, 0.6.0, posted just a few days ago, fixes this and several other problems. All examples now use glasses defined in the Examples module rather than Schott glasses. 

If you are using the latest version of the software you could use the these glasses instead of Schott and your code should run: OpticSim.Examples.Examples_N_BK7 
OpticSim.Examples.Examples_N_SK16
OpticSim.Examples.Examples_N_SF2 
OpticSim.Examples.Examples_N_SF14

These are exactly equivalent to the corresponding Schott glasses.

**Comment by highflyer737** [comment] 2022-05-12 20:40
Thanks for the fast response @BrianGun!

Well I'm geting a libGL error now which probably means *this* issue is fixed and can be closed.

Thanks

**Closed** 2022-05-12 20:45 UTC
