### ISSUE TITLE
OpenGL fails on Windows tests

### ISSUE THREAD

**Issue by BrianGun** [microsoft/OpticSim.jl#74] opened 2021-04-01 17:40 UTC
**Describe the bug**
OpenGL doesn't load properly on the Windows VM.

**To Reproduce**
make a pull request.

**Expected behavior**
OpenGL should run headless on the Windows VM's on github but doesn't. This has been problematic. We don't need the visualization results for Windows since our documentation is generated on the Linux VM run. Turn this off for Windows so no calls to Vis are made in the tests.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Julia version [e.g. 1.5.2]
 - OpticSim.jl version [e.g. 0.3.1]

**Additional context**

**Comment by alfredclwong** [comment] 2021-04-01 18:04
This is a duplicate of #72.

**Closed by alfredclwong** 2021-04-01 18:04 UTC
