### ISSUE TITLE
TaskFailedException

### ISSUE THREAD

**Issue by klaff** [microsoft/OpticSim.jl#50] opened 2021-03-24 16:07 UTC
Running the following under Julia 1.6 rc3, within Pluto:
```
Vis.draw(SphericalLens(OpticSim.GlassCat.SCHOTT.N_BK7, 0.0, 10.0, 10.0, 5.0, 5.0))
```

gives the following trace:
```
TaskFailedException

nested task error: TaskFailedException

Stacktrace:

[1] wait

@ .\task.jl:317 [inlined]

[2] fetch

@ .\task.jl:332 [inlined]

[3] makemeshi(a::OpticSim.IntersectionNode{Float64, OpticSim.LeafNode{Float64, OpticSim.Sphere{Float64, 3}}, OpticSim.LeafNode{Float64, OpticSim.SphericalCap{Float64}}}, subdivisions::Int64)

@ OpticSim ~\.julia\packages\OpticSim\xlzDG\src\Geometry\CSG\CSG.jl:535

[4] makemesh(c::OpticSim.IntersectionNode{Float64, OpticSim.LeafNode{Float64, OpticSim.Sphere{Float64, 3}}, OpticSim.LeafNode{Float64, OpticSim.SphericalCap{Float64}}}, subdivisions::Int64)

@ OpticSim ~\.julia\packages\OpticSim\xlzDG\src\Geometry\CSG\CSG.jl:568

[5] (::OpticSim.var"#92#94"{OpticSim.IntersectionNode{Float64, OpticSim.IntersectionNode{Float64, OpticSim.LeafNode{Float64, OpticSim.Sphere{Float64, 3}}, OpticSim.LeafNode{Float64, OpticSim.SphericalCap{Float64}}}, OpticSim.LeafNode{Float64, OpticSim.Cylinder{Float64, 3}}}, Int64})()

@ OpticSim .\threadingconstructs.jl:169

nested task error: BoundsError: attempt to access 1-element Vector{Dict{DataType, OpticSim.TrianglePool}} at index [2]

Stacktrace:

[1] getindex

@ .\array.jl:801 [inlined]

[2] newintrianglepool!(::Type{Float64}, tid::Int64) (repeats 2 times)

@ OpticSim ~\.julia\packages\OpticSim\xlzDG\src\Geometry\CSG\CSG.jl:343

[3] triangulate(surf::OpticSim.Sphere{Float64, 3}, subdivisons::Int64, extensionu::Bool, extensionv::Bool, radialu::Bool, radialv::Bool) (repeats 2 times)

@ OpticSim ~\.julia\packages\OpticSim\xlzDG\src\Geometry\Surface.jl:189

[4] makemeshi(a::OpticSim.LeafNode{Float64, OpticSim.Sphere{Float64, 3}}, subdivisions::Int64)

@ OpticSim ~\.julia\packages\OpticSim\xlzDG\src\Geometry\CSG\CSG.jl:559

[5] makemesh(c::OpticSim.LeafNode{Float64, OpticSim.Sphere{Float64, 3}}, subdivisions::Int64)

@ OpticSim ~\.julia\packages\OpticSim\xlzDG\src\Geometry\CSG\CSG.jl:568

[6] (::OpticSim.var"#92#94"{OpticSim.IntersectionNode{Float64, OpticSim.LeafNode{Float64, OpticSim.Sphere{Float64, 3}}, OpticSim.LeafNode{Float64, OpticSim.SphericalCap{Float64}}}, Int64})()

@ OpticSim .\threadingconstructs.jl:169
```
This doesn't happen if I run the code from the command line (outside of Pluto), but it also doesn't happen on another computer under Pluto (both 1.6 rc3, Windows 10), so it's not obvious to me that it is a Pluto incompatibility.

output from `versioninfo()`:
```
      From worker 2:    Julia Version 1.6.0-rc3
      From worker 2:    Commit 23267f0d46 (2021-03-16 17:04 UTC)
      From worker 2:    Platform Info:
      From worker 2:      OS: Windows (x86_64-w64-mingw32)
      From worker 2:      CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
      From worker 2:      WORD_SIZE: 64
      From worker 2:      LIBM: libopenlibm
      From worker 2:      LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
      From worker 2:    Environment:
      From worker 2:      JULIA_REVISE_WORKER_ONLY = 1
```

**Comment by alfredclwong** [comment] 2021-03-24 16:37
Thanks for trying out our code, and for the bug report!

@BrianGun it seems like an error to do with the multi-threaded triangle pooling. I didn't write this - is it possible that there's some race condition here?

**Comment by klaff** [comment] 2021-03-24 16:41
If you can't reproduce this I am game to try to do some experiments. Can I tell it I only have one core?

**Comment by BrianGun** [comment] 2021-03-24 16:47
We have only done very limited testing on 1.6. Does this happen in 1.5.2-1.5.4?

**Comment by BrianGun** [comment] 2021-03-24 17:03
@friggog you might want to take a look at this.

**Comment by friggog** [comment] 2021-03-24 17:15
Hmm, yeah first thing would be try on 1.5.X. I tested on 1.6.0 a good while ago and didn't have any problems but wouldn't be surprised at all if that has changed. As brian suggests I suspect running on a single thread will work too.

I guess it will be worth starting to migrate to/support 1.6 properly soonish. Not sure how close to release it is yet

**Comment by klaff** [comment] 2021-03-24 17:40
Same failure on 1.5.3 (still multithreaded).

**Comment by rambunctiousapple** [comment] 2021-03-24 17:59
I don't see the error on my linux machine running 1.5.3. @klaff MWE works fine and the spherical lens renders properly. 

@alfredclwong or @friggog do either of you have 1.6rc installed on your machine? Could you see if you get the error?

**Comment by klaff** [comment] 2021-03-24 18:01
Hey, I think this may be a Pluto issue after all.  See https://github.com/fonsp/Pluto.jl/issues/300.

If I start Pluto by `import Pluto; Pluto.run(workspace_use_distributed=false)` then the I get a nice 3D view of a lens!

I don't understand why it fails on one machine (6/12 cores) and not on another (4/8 cores).

**Comment by BrianGun** [comment] 2021-03-24 18:57
is it okay to close this issue? The note about distributed and Pluto should be retained somewhere so other people don't have the same problem. Where is the best place to put it?

**Comment by alfredclwong** [comment] 2021-03-24 19:12
I'd suggest adding a "Known Issues" page to the docs

**Comment by alfredclwong** [comment] 2021-03-24 19:20
I'll also add some nightly tests to the strategy matrix in CI.yml tomorrow. I won't make them compulsory, but they'll be good to have.

**Comment by klaff** [comment] 2021-03-24 19:21
Now I'm not sure. Looking around the repo, I see there's work relating to Pluto here: https://github.com/microsoft/OpticSim.jl/pull/46/commits/63612b9ec0574d8f959aa66ede6a2655d30c9fd8

**Comment by fonsp** [comment] 2021-03-25 14:29
`import Pluto; Pluto.run(workspace_use_distributed=false)` also means that Pluto does not control the number of `threads`, try setting the number of threads in the REPL and in Pluto to see if that is the problem. You can use `Pluto.Configuration.roughly_the_number_of_physical_cpu_cores()` to see the default value used by Pluto, or `Pluto.run(threads="1")` to change the number for notebook processes.

**Comment by BrianGun** [comment] 2021-03-26 12:52
@klaff @fonsp is the conclusion that this is an issue with Pluto? Can I close this issue or do we need to hunt for a bug in our code?

**Comment by klaff** [comment] 2021-03-26 13:08
I haven't had time to try Fons' suggestions and I'm also not sure how to interpret the results, meaning I'm not sure how to divide and conquer this to say it is a Pluto problem or a OpticSim problem. It may be a few days before I can mess with it some more.

I don't think it makes sense for you to spend time hunting if I can't make it replicate outside of Pluto, and I do have a workaround for the moment. If you could leave it open a few days maybe I'll learn more, but if it's annoying to have it lingering then close it and if I learn that there is a way to fix it within OpticSim I'll open a new issue.

**Comment by BrianGun** [comment] 2021-03-26 16:02
We'll leave it open for a few more days then close it if we don't hear anything from you. Glad to hear you have a workaround.

**Comment by klaff** [comment] 2021-03-27 20:38
I made it happen without Pluto.

MWE1.jl:
```
import Pkg
Pkg.activate(mktempdir())
Pkg.add("DataFrames"); using DataFrames
Pkg.add("OpticSim"); using OpticSim

sys = AxisymmetricOpticalSystem(
    DataFrame(Surface = [:Object, 1, 2, 3, :Stop, 5, 6, :Image],
              Radius = [Inf, 26.777,  66.604, -35.571, 35.571, 35.571, -26.777, Inf],
              Thickness = [Inf, 4.0, 2.0, 4.0, 2.0, 4.0, 44.748, missing],
              Material = [OpticSim.GlassCat.Air, OpticSim.GlassCat.SCHOTT.N_SK16,
						OpticSim.GlassCat.Air, OpticSim.GlassCat.SCHOTT.N_SF2, 
						OpticSim.GlassCat.Air, OpticSim.GlassCat.SCHOTT.N_SK16,
						OpticSim.GlassCat.Air, missing],
              SemiDiameter = [Inf, 8.580, 7.513, 7.054, 6.033, 7.003, 7.506, 15.0]))

f1 = HexapolarField(sys, collimated = true, samples = 4, sourcenum = 1)

Vis.drawtracerays(sys, raygenerator = f1, test = true, trackallrays = true,
	colorbysourcenum = true, resolution = (1000, 700))
```
Run from command line by:
```
julia -i -t 2 MWE1.jl
```
results in:
```
ERROR: LoadError: TaskFailedException
Stacktrace:
  [1] wait
    @ .\task.jl:317 [inlined]
  [2] fetch
    @ .\task.jl:332 [inlined]
  [3] makemeshi(a::OpticSim.IntersectionNode{Float64, OpticSim.IntersectionNode{Float64, OpticSim.LeafNode{Float64, Sphere{Float64, 3}}, OpticSim.LeafNode{Float64, SphericalCap{Float64}}}, OpticSim.LeafNode{Float64, Cylinder{Float64, 3}}}, subdivisions::Int64)
    @ OpticSim ~\.julia\packages\OpticSim\4qItW\src\Geometry\CSG\CSG.jl:535
  [4] makemesh(c::OpticSim.IntersectionNode{Float64, OpticSim.IntersectionNode{Float64, OpticSim.LeafNode{Float64, Sphere{Float64, 3}}, OpticSim.LeafNode{Float64, SphericalCap{Float64}}}, OpticSim.LeafNode{Float64, Cylinder{Float64, 3}}}, subdivisions::Int64)
    @ OpticSim ~\.julia\packages\OpticSim\4qItW\src\Geometry\CSG\CSG.jl:568
  [5] #draw!#26
    @ ~\.julia\packages\OpticSim\4qItW\src\Visualization\Visualization.jl:408 [inlined]
  [6] draw!(scene::AbstractPlotting.MakieLayout.LScene, ass::LensAssembly; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ OpticSim.Vis ~\.julia\packages\OpticSim\4qItW\src\Visualization\Visualization.jl:437
  [7] draw!
    @ ~\.julia\packages\OpticSim\4qItW\src\Visualization\Visualization.jl:436 [inlined]
  [8] draw!(scene::AbstractPlotting.MakieLayout.LScene, sys::CSGOpticalSystem{Float64, Float32, Rectangle{Float64}, LensAssembly}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ OpticSim.Vis ~\.julia\packages\OpticSim\4qItW\src\Visualization\Visualization.jl:447
  [9] draw!
    @ ~\.julia\packages\OpticSim\4qItW\src\Visualization\Visualization.jl:447 [inlined]
 [10] #draw!#31
    @ ~\.julia\packages\OpticSim\4qItW\src\Visualization\Visualization.jl:451 [inlined]
 [11] draw!
    @ ~\.julia\packages\OpticSim\4qItW\src\Visualization\Visualization.jl:451 [inlined]
 [12] drawtracerays!(scene::AbstractPlotting.MakieLayout.LScene, system::AxisymmetricOpticalSystem{Float64, CSGOpticalSystem{Float64, Float32, Rectangle{Float64}, LensAssembly}}; raygenerator::RayListSource{Float64}, test::Bool, trackallrays::Bool, colorbysourcenum::Bool, colorbynhits::Bool, rayfilter::typeof(OpticSim.Vis.onlydetectorrays), verbose::Bool, drawsys::Bool, drawgen::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ OpticSim.Vis ~\.julia\packages\OpticSim\4qItW\src\Visualization\Visualization.jl:483
 [13] #drawtracerays#32
    @ ~\.julia\packages\OpticSim\4qItW\src\Visualization\Visualization.jl:472 [inlined]
 [14] top-level scope
    @ D:\julia\eclipse\MWE1.jl:18

    nested task error: TaskFailedException
    Stacktrace:
     [1] wait
       @ .\task.jl:317 [inlined]
     [2] fetch
       @ .\task.jl:332 [inlined]
     [3] makemeshi(a::OpticSim.IntersectionNode{Float64, OpticSim.LeafNode{Float64, Sphere{Float64, 3}}, OpticSim.LeafNode{Float64, SphericalCap{Float64}}}, subdivisions::Int64)
       @ OpticSim ~\.julia\packages\OpticSim\4qItW\src\Geometry\CSG\CSG.jl:535
     [4] makemesh(c::OpticSim.IntersectionNode{Float64, OpticSim.LeafNode{Float64, Sphere{Float64, 3}}, OpticSim.LeafNode{Float64, SphericalCap{Float64}}}, subdivisions::Int64)
       @ OpticSim ~\.julia\packages\OpticSim\4qItW\src\Geometry\CSG\CSG.jl:568
     [5] (::OpticSim.var"#91#93"{OpticSim.IntersectionNode{Float64, OpticSim.IntersectionNode{Float64, OpticSim.LeafNode{Float64, Sphere{Float64, 3}}, OpticSim.LeafNode{Float64, SphericalCap{Float64}}}, OpticSim.LeafNode{Float64, Cylinder{Float64, 3}}}, Int64})()
       @ OpticSim .\threadingconstructs.jl:169

        nested task error: BoundsError: attempt to access 1-element Vector{Dict{DataType, OpticSim.TrianglePool}} at index [2]
        Stacktrace:
         [1] getindex
           @ .\array.jl:801 [inlined]
         [2] newintrianglepool!(::Type{Float64}, tid::Int64) (repeats 2 times)
           @ OpticSim ~\.julia\packages\OpticSim\4qItW\src\Geometry\CSG\CSG.jl:343
         [3] triangulate(surf::Sphere{Float64, 3}, subdivisons::Int64, extensionu::Bool, extensionv::Bool, radialu::Bool, radialv::Bool) (repeats 2 times)
           @ OpticSim ~\.julia\packages\OpticSim\4qItW\src\Geometry\Surface.jl:189
         [4] makemeshi(a::OpticSim.LeafNode{Float64, Sphere{Float64, 3}}, subdivisions::Int64)
           @ OpticSim ~\.julia\packages\OpticSim\4qItW\src\Geometry\CSG\CSG.jl:559
         [5] makemesh(c::OpticSim.LeafNode{Float64, Sphere{Float64, 3}}, subdivisions::Int64)
           @ OpticSim ~\.julia\packages\OpticSim\4qItW\src\Geometry\CSG\CSG.jl:568
         [6] (::OpticSim.var"#91#93"{OpticSim.IntersectionNode{Float64, OpticSim.LeafNode{Float64, Sphere{Float64, 3}}, OpticSim.LeafNode{Float64, SphericalCap{Float64}}}, Int64})()
           @ OpticSim .\threadingconstructs.jl:169
in expression starting at D:\julia\eclipse\MWE1.jl:18
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia>
```
If I run
```
julia -i MWE1.jl
```
I get a nice plot of a triplet!

**Comment by klaff** [comment] 2021-03-27 21:07
So after a little more work and rereading Fons' comments above - what I'm seeing is that I can't run OpticSim threaded on this machine. When I run it under Pluto, Pluto was setting the number of threads to 6. When I ran it at the command line I was getting single threaded (didn't have the environment variable set on this machine).

**Comment by alfredclwong** [comment] 2021-03-27 22:23
It seems that this is a problem with our code, and it was only noticed through Pluto because of the multi-threaded default behaviour.

I can't reproduce the error using your script. This might be indicative of the fact that we're dealing with a race condition, but from the looks of it no data is shared between threads so this seems unlikely.

My best guess is that it's a problem with `const threadedtrianglepool`, a vector which gets accessed by index according to `Threads.threadid()`. The stack trace suggests that Thread #&#x2060;2 is trying to access index 2, but `threadedtrianglepool` is only length 1. I imagine that, with the pre-compilation changes in Julia 1.6+, the `threadedtrianglepool` gets created by a single-threaded worker during compile-time, so `Threads.nthreads()` is equal to 1. When you run the code with `julia -t2`, `nthreads` is now 2, but `threadedtrianglepool` was fixed during compile-time*, which leads to the error.

@klaff, could you try to inspect these variables (`threadedtrianglepool` and `nthreads`) using `@show` macros?

*To be honest, I haven't read up on the Julia compiler, so this could be very wrong, but I'd imagine that consts are pre-calculated and fixed at compile-time.

**Comment by klaff** [comment] 2021-03-27 22:54
Interesting. I did replicate the failure on 1.5.3, so it's not specific to 1.6.0. I will keep debugging but it may again be a few days. Thanks.

**Comment by BrianGun** [comment] 2021-03-28 18:14
It's an error in the initialization of threadedtrianglepool. The size of this array is being set in the precompilation environment, when it should be set in the load time environment in an __init__ function for the OpticSim module.

The problem didn't surface on any of our machines because our default (i.e., precompilation) environments all have the number of threads set to some number much larger than 2, or even 6. 

Our caches are therefore bigger than they need to be when julia is started with a smaller number of threads so there isn't an out of bounds array access.

There may be other caches that have the same problem. We'll hunt them down and get a fix out within a few days.

**Comment by BrianGun** [comment] 2021-03-28 22:31
@klaff could you confirm this latest PR fixes the problem for you?

**Comment by klaff** [comment] 2021-03-28 23:33
> @klaff could you confirm this latest PR fixes the problem for you?

I can't break it now. Single or multithreaded from command line and works in Pluto now. Thank you!

**Comment by BrianGun** [comment] 2021-03-29 03:05
Great! I'll close this issue now.

**Closed by BrianGun** 2021-03-29 03:05 UTC
Labels: bug
